package isamm.projet.beans;
// Generated 22 nov. 2017 00:55:58 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lignematierefiliere generated by hbm2java
 */
@Entity
@Table(name = "lignematierefiliere", catalog = "tp2hibernate")
public class Lignematierefiliere implements java.io.Serializable {

	private Integer id;
	private Filiere filiere;
	private Matiere matiere;
	private Integer masseHoraire;

	public Lignematierefiliere() {
	}

	public Lignematierefiliere(Filiere filiere, Matiere matiere) {
		this.filiere = filiere;
		this.matiere = matiere;
	}

	public Lignematierefiliere(Filiere filiere, Matiere matiere, Integer masseHoraire) {
		this.filiere = filiere;
		this.matiere = matiere;
		this.masseHoraire = masseHoraire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFiliere", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMatiere", nullable = false)
	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

	@Column(name = "masseHoraire")
	public Integer getMasseHoraire() {
		return this.masseHoraire;
	}

	public void setMasseHoraire(Integer masseHoraire) {
		this.masseHoraire = masseHoraire;
	}

}
